### ISSUE TITLE
Add healthcheck URL for load balancers

### ISSUE THREAD

**Issue by gtaylor** [graylog-labs/graylog2-web-interface#1511]
We've got a load balancer parked in front of our graylog-web instance, but are having to hit the login page to make sure that things are up. Would be great if graylog-web had a URL endpoint like graylog-server does for health checks.

**Comment by tboeghk** [comment]
:+1:

**Comment by adaofeliz** [comment]
+1

**Comment by sankalp-khare** [comment]
+1

@gtaylor , what is the exact configuration you're using? I'm using [the ITOC AMI\(http://itoc.com.au/community/oss/amis/graylog2) and nothing seems to be working :(

**Comment by gtaylor** [comment]
![screenshot from 2015-10-12 11 51 57](https://cloud.githubusercontent.com/assets/75556/10435880/aebe1e9a-70d7-11e5-927b-5ae6f0e678e8.png)

This is working for us.

**Comment by julienlau** [comment]
+1
/login?destination=%2F does not make it with graylog 2.2 docker instanciated on DCOS

**Comment by joschi** [comment]
Since the Graylog web interface has been merged into the core in Graylog 2.0.0, you can use the known health check resource at `/system/lbstatus`:

http://docs.graylog.org/en/2.3/pages/configuration/load_balancers.html#load-balancer-state

**Comment by julienlau** [comment]
I tried this, but api is not accessible by default.
I do not remember if the problem was that credentials are necessary to reach the api healthcheck or if it was that you cannot configure the api to be ON on the yaml file loaded at startup of graylog.

**Comment by joschi** [comment]
The `/system/lbstatus` resource in the Graylog REST API is accessible without authentication.
