### ISSUE TITLE
Appending new data to existing extractor data.

### ISSUE THREAD

**Issue by timukas** [graylog-labs/graylog2-web-interface#767]
Hi,

I'm extracting some data from logs and storing it in "params" field. This works well.

Now i'm extracting another piece of data and storing it to same "params" field.
I assumed that new data will be appended to existing, but no. Old data is overwritten by new data.

Instead of making new fields for some extracted data it would be wise to append data to existing field. This might help avoiding huge number of different fields.

regards,

**Comment by irgendwr** [comment]
Hi, I was wondering if something changed regarding this feature request.
I'd find it useful to have an 'append' option (like @timukas suggested) to build a more human-readable message out of already extracted fields (from a JSON message for example).
_(I know this is quite an old issue but I thought I'd ask here first before creating a new one)_

Edit: just noticed that this repo is inactive, oops ^^

**Comment by joschi** [comment]
You can already do this with the [Processing Pipelines](http://docs.graylog.org/en/2.2/pages/pipelines.html).
