### ISSUE TITLE
Extractor condition is restricted to same field value

### ISSUE THREAD

**Issue by kroepke** [graylog-labs/graylog2-web-interface#798]
When receiving messages from various sources via one input, one could like to set up conditions that act like a switch based on a specific field value.

For example, two sources send messages in slightly different formats.
Which kind of message format needs to be applied depends on the content of a field in the message, like logformat:"type_a".
When setting up a condition on an extractor it can only check for a string or regex match in the same field as the extractor will run on.

Make it possible to check contents of different fields, too.

**Comment by sapk** [comment]
Maybe a good solution could be to be able to apply extractor on a stream like a input ?

**Comment by ScreamZ** [comment]
Any news on this, or good pattern ?

**Comment by joschi** [comment]
@ScreamZ Take a look at the message processing pipelines: http://docs.graylog.org/en/2.2/pages/pipelines.html

**Comment by joschi** [comment]
I'm closing this issue. The requirements are met by the processing pipelines.
